title: Mathématiques
description: Cours de Mathématiques
theme: just-the-docs

url: https://HowlCraft.github.io/just-docs

aux_links:
  Template Repository: https://github.com/HowlCraft/just-docs
  
math: mathjax

color_scheme: dawn

callouts:
  note:
    title: Remarque
    color: pink
    opacity: 0.3
  warning:
    title: Attention
    color: red

